---
abstract: 'sends Catalyst log messages to a FirePHP console'
author:
  - 'Sebastian Willert, C<willert@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-FirePHP
no_index:
  directory:
    - inc
    - t
recommends:
  Catalyst::Log::Log4perl: 0
  DBIx::Class::Storage::Statistics::SimpleTable: 0
requires:
  Catalyst: 0
  Class::BlackHole: 0
  FirePHP::Dispatcher: 0.02
  Scope::Guard: 0
  perl: 5.8.5
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_02
